//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class DialoguePrompt : MonoBehaviour
{
	string NPC;
	bool spawner = true;
	public GameObject thePrefab;
	public GameObject myInstance;
	public GameObject target;
	//public GameObject target;
	Vector3 targetPos;
	//GameObject target = GameObject.FindWithTag ("Player");
	/*public DialoguePrompt (string name)
	{
		NPC = name;
	}*/
	//float timeLeft = 20;
	void TheStart(string name){
		NPC = name;

	}

	void Start(){
		target = GameObject.FindWithTag ("Player");
	}

	void Update () {
		//print (target.transform.position.x);
		//print (Vector3.Distance (target.transform.position, transform.position));
		if (spawner == true) {
			print(NPC);
			print ("spawning textbox");
			Vector3 temp = transform.position;
			temp.x = transform.position.x - 5;
			temp.y = transform.position.y + 6;
			myInstance = Instantiate (thePrefab, temp, transform.rotation) as GameObject;
			spawner = false;
			myInstance.SendMessage ("TheStart", NPC);
			print ("destroying prompt from update");
			//Destroy (gameObject);
			//renderer.enabled = false;
		}
		//print (Vector3.Distance (target.transform.position, transform.position));
		/*if (Vector3.Distance (target.transform.position, transform.position) > 20) {
			print ("Destroying object from proximity");
			print (target.transform.position.x);
			print (transform.position.x);
			print (Vector3.Distance (target.transform.position, transform.position));
			Destroy (gameObject); 
			//renderer.enabled = false;
		}*/
	}

	/*void OnCollisionEnter2D (Collision2D col){
		print ("Collision with Prompt");
	}*/

	/*void OnCollisionExit2D (Collision2D col){
		print ("Destroying Prompt from collision exit");
		Destroy (gameObject);
	}*/



}


