//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;



public class DialogueCollider : MonoBehaviour {

	public GameObject thePrefab;
	private GameObject instance;
	//public GameObject player; 
	//public string NPC = "bob";
	public int speechNumbers = 3;
	private int currentSpeech = 0;
	private bool activated = false;

	void FixedUpdate()
	{
		if(activated && Input.GetKeyUp(KeyCode.E))
		{
			currentSpeech = (currentSpeech + 1) % speechNumbers;
			instance.SendMessage("TextDisplay", currentSpeech);
		}
	}

	void OnTriggerEnter2D (Collider2D col)
	{
		if(col.tag == "Player")
		{
			//print (NPC);
			//print ("collision with NPC");
			//player = GameObject.Find ("Aliver");
			//player.GetComponent<AliverController> ().enabled = false;
			//player.rigidbody2D.velocity.Set (0, 0);
			/*if (Input.GetKeyDown (KeyCode.F) && spawnLimit == 0) {
				print ("Textbox Spawn");
				Vector3 temp = transform.position;
				temp.x = transform.position.x - 5;
				temp.y = transform.position.y + 6;
				UnityEngine.Quaternion temp2 = transform.rotation;
				temp2.z = transform.rotation.z - 90;
				instance = Instantiate (thePrefab, temp, temp2) as GameObject;
				spawnLimit = 1;
			}*/
			if (!activated) {
				Vector3 temp = transform.position;
				temp.x = transform.position.x + 1;
				Quaternion temp2 = transform.rotation;
				temp2.z = transform.rotation.z - 90;
				print ("spawning prompt");
				instance = Instantiate (thePrefab, temp, temp2) as GameObject;
				instance.transform.parent = transform;
				instance.SendMessage ("TheStart", gameObject.name);
				instance.SendMessage("TextDisplay", currentSpeech);
				activated = true;
			}
		}
	}

	void OnTriggerExit2D (Collider2D col)
	{
		if(col.tag == "Player")
		{
			print ("Exit");
			if (activated) {
				Destroy(instance);
				activated = false;
			}
		}
	}
}

