//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;



public class DialogueCollider : MonoBehaviour {

	public GameObject thePrefab;
	public int spawnLimit = 0;
	public GameObject instance;
	public GameObject player; 
	public string NPC = "bob";


	void OnCollisionEnter2D (Collision2D col)
	{
		//print (NPC);
		print ("collision with NPC");
		//player = GameObject.Find ("Aliver");
		//player.GetComponent<AliverController> ().enabled = false;
		//player.rigidbody2D.velocity.Set (0, 0);
		/*if (Input.GetKeyDown (KeyCode.F) && spawnLimit == 0) {
			print ("Textbox Spawn");
			Vector3 temp = transform.position;
			temp.x = transform.position.x - 5;
			temp.y = transform.position.y + 6;
			UnityEngine.Quaternion temp2 = transform.rotation;
			temp2.z = transform.rotation.z - 90;
			instance = Instantiate (thePrefab, temp, temp2) as GameObject;
			spawnLimit = 1;
		}*/
		if (spawnLimit == 0) {
			Vector3 temp = transform.position;
			temp.x = transform.position.x + 1;
			Quaternion temp2 = transform.rotation;
			temp2.z = transform.rotation.z - 90;
			print ("spawning prompt");
			instance = Instantiate (thePrefab, temp, temp2) as GameObject;
			instance.transform.parent = transform;
			instance.SendMessage ("TheStart", NPC);
			spawnLimit = 1;
		}
	}

	void OnCollisionExit2D (Collision2D col)
	{
		print ("Exit");
		if (spawnLimit == 1) {
			//Destroy(instance);
			spawnLimit = 0;
		}

	}
}

