//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class MyNPC : MonoBehaviour {

	public Animator anim;
	string name;
	int speechNumber;
		
	void Start(){

		name = "bob";
		speechNumber = 1;
		//here get texture/animator
			
			
	}
		
	void OnTriggerEnter2D(Collider2D col){
			
		//play sound
		//spawn new object here
		//will need to create new dialogue box option
		//figure out xml later
			
	}
}



